[package]
name = "vad"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }

ndarray = "0.16"
ort = { version = "=2.0.0-rc.9", features = ["load-dynamic"] }

[dev-dependencies]
hypr-data = { workspace = true }
