[target.'cfg(all(windows, target_env = "msvc"))']
rustflags = [
  "-C",
  "target-feature=-crt-static",
  "-C",
  "link-arg=/nodefaultlib:msvcrt",
  "-C",
  "link-arg=/defaultlib:msvcrtd",
]

[env]
# Force all C/C++ compilation to use debug runtime
CFLAGS = { value = "/MDd /D_DEBUG /Od", force = true }
CXXFLAGS = { value = "/MDd /D_DEBUG /Od", force = true }

# CMake configuration for debug runtime
CMAKE_CXX_FLAGS = { value = "/MDd /D_DEBUG /Od", force = true }
CMAKE_C_FLAGS = { value = "/MDd /D_DEBUG /Od", force = true }
CMAKE_MSVC_RUNTIME_LIBRARY = { value = "MultiThreadedDebugDLL", force = true }
CMAKE_BUILD_TYPE = { value = "Debug", force = true }

# Global debug flags
DEBUG = { value = "1", force = true }
_DEBUG = { value = "1", force = true }

# ORG
ORT_DYLIB_PATH = { value = "./dlls/onnxruntime.dll", force = true }
