[target.'cfg(all(windows, target_env = "msvc"))']
rustflags = [
  "-C",
  "target-feature=-crt-static",
  "-C",
  "link-arg=/nodefaultlib:msvcrt",
  "-C", 
  "link-arg=/defaultlib:msvcrtd",
]

[env]
# Force all C/C++ compilation to use debug runtime
CFLAGS = "/MDd /D_DEBUG /Od"
CXXFLAGS = "/MDd /D_DEBUG /Od"

# Force cc crate to use debug runtime for all targets
CC_x86_64-pc-windows-msvc = "cl"
CXX_x86_64-pc-windows-msvc = "cl"
CFLAGS_x86_64-pc-windows-msvc = "/MDd /D_DEBUG /Od"
CXXFLAGS_x86_64-pc-windows-msvc = "/MDd /D_DEBUG /Od"
CFLAGS_x86_64_pc_windows_msvc = "/MDd /D_DEBUG /Od"
CXXFLAGS_x86_64_pc_windows_msvc = "/MDd /D_DEBUG /Od"

# Target-specific compiler flags
TARGET_CFLAGS = "/MDd /D_DEBUG /Od"
TARGET_CXXFLAGS = "/MDd /D_DEBUG /Od"

# Force CMake to use debug runtime
CMAKE_CXX_FLAGS = "/MDd /D_DEBUG"
CMAKE_C_FLAGS = "/MDd /D_DEBUG"
CMAKE_CXX_FLAGS_DEBUG = "/MDd /D_DEBUG /Od /Zi"
CMAKE_C_FLAGS_DEBUG = "/MDd /D_DEBUG /Od /Zi"
CMAKE_CXX_FLAGS_RELEASE = "/MDd /D_DEBUG /O2"
CMAKE_C_FLAGS_RELEASE = "/MDd /D_DEBUG /O2"
CMAKE_MSVC_RUNTIME_LIBRARY = "MultiThreadedDebugDLL"
CMAKE_BUILD_TYPE = "Debug"

# Force debug configuration globally
DEBUG = "1"
NDEBUG = ""
_DEBUG = "1"
MSVC_RUNTIME = "dynamic-debug"
MSVC_DEBUG = "1"

# For whisper.cpp
WHISPER_CFLAGS = "/MDd /D_DEBUG"
WHISPER_CXXFLAGS = "/MDd /D_DEBUG"