[package]
name = "oauth-callback"
version = "0.1.0"
edition = "2021"

[dependencies]
hypr-oauth-core = { workspace = true }
hypr-oauth-providers = { workspace = true }

tower = { workspace = true }

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_qs = { workspace = true }

base64 = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true, features = ["v4"] }

futures-util = { workspace = true }
reqwest = { workspace = true }
tracing = { workspace = true }
