[target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]
env = { CFLAGS = "/MT", CXXFLAGS = "/MT" }

[target.aarch64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]
env = { CFLAGS = "/MT", CXXFLAGS = "/MT" }
