[package]
name = "ws"
version = "0.1.0"
edition = "2021"

[features]
default = ["client"]
client = []
server = []

[dependencies]
bytes = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }

async-stream = { workspace = true }
backon = { workspace = true }
futures-util = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "time", "sync", "macros"] }
tracing = { workspace = true }

once_cell = { workspace = true }

[target.'cfg(windows)'.dependencies]
tokio-tungstenite = { workspace = true, features = ["native-tls"] }

[target.'cfg(not(windows))'.dependencies]  
tokio-tungstenite = { workspace = true, features = ["native-tls-vendored"] }
