on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/poetry_install
      - run: poetry run python scripts/pre_build.py
