on:
  workflow_dispatch:
  release:
    types:
      - published
      - prereleased
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos"
            target: "aarch64-apple-darwin"
            runner: "macos-latest"
          - platform: "macos"
            target: "x86_64-apple-darwin"
            runner: "macos-latest"
          - platform: "windows"
            target: "x86_64-pc-windows-msvc"
            runner: "windows-latest"
          - platform: "linux"
            target: "x86_64-unknown-linux-gnu"
            runner: "ubuntu-latest"
          - platform: "linux"
            target: "x86_64-unknown-linux-musl"
            runner: "ubuntu-latest"
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - if: matrix.platform == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev libasound2-dev
          if [[ "${{ matrix.target }}" == *"musl"* ]]; then
            sudo apt-get install -y musl-tools musl-dev
          fi
      - uses: ./.github/actions/rust_install
        with:
          platform: ${{ matrix.platform }}
      - run: cargo build --release --bin owhisper-server --target ${{ matrix.target }}
        env:
          PKG_CONFIG_ALLOW_CROSS: ${{ matrix.target == 'x86_64-unknown-linux-musl' && '1' || '' }}
          PKG_CONFIG_ALL_STATIC: ${{ matrix.target == 'x86_64-unknown-linux-musl' && '1' || '' }}

      - id: prepare_artifacts
        shell: bash
        run: |
          mkdir -p artifacts
          cp target/${{ matrix.target }}/release/owhisper-server* artifacts/
          cd artifacts
          for file in owhisper-server*; do
            if [ -f "$file" ]; then
              mv "$file" "${file%%.*}-${{ matrix.target }}${file#owhisper-server}"
            fi
          done

      - uses: actions/upload-artifact@v4
        with:
          name: owhisper-server-${{ matrix.target }}
          path: artifacts/*
          retention-days: 7

      - if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
