name: R2 S3 Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
          source: "s3://hyprnote-cache2/v0/binaries/stt"
          dest: "./stt"
          aws_s3_endpoint: ${{ secrets.CLOUDFLARE_R2_ENDPOINT_URL }}
          aws_region: auto
      - run: ls -l
